apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-reset-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: password-reset
  template:
    metadata:
      labels:
        app: password-reset
    spec:
      containers:
      - name: password-reset-container
        image: password-reset-app:v1
        imagePullPolicy: Never
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 30; done"]
        ports:
        - containerPort: 8080
